name: Publish NuGet Package

on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish to NuGet

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v4

      - name: Run GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Pack project with GitVersion version
        run: dotnet pack --configuration Release --no-build -o out /p:PackageVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}

      - name: Push to NuGet
        run: dotnet nuget push out/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
